spring.application.name=16_customQueries

#db conig
spring.datasource.url= jdbc:postgresql://localhost:5432/custom_queries
spring.datasource.username=postgres
spring.datasource.password=Viraj

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect