spring.application.name=22_student_management_system


spring.datasource.url=jdbc:postgresql://localhost:5432/student_app
spring.datasource.username=postgres
spring.datasource.password=Viraj

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp


#SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=virajst21hite@student.mes.ac.in
spring.mail.password=qxueovubcmrlsxtz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.requires=true

#spring.mail.properties.mail.debug=true