spring.application.name=23_JWT_Authentication

spring.datasource.url= jdbc:postgresql://localhost:5432/jwt_db
spring.datasource.username=postgres
spring.datasource.password=Viraj

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
